### ISSUE TITLE
Ugify error Expo v19.0.0

### ISSUE THREAD

**Issue by chinclubi** [lelandrichardson/react-primitives#83]
Hi, 
I'm using `react-primitives` on Expo v19.0.0 with **enabling Minify mode (Uglify)**. I found that `react-primitives` cause the error:

```javascript
Error: Uncaught error in the transformer worker: D:\Office\learn\test\node_modules\metro-bundler\build\transformer.js
    at _transform.then.catch.error (D:\Office\learn\test\node_modules\metro-bundler\build\JSTransformer\index.js:147:31)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

_This error is gone if you disable Minify mode._

You can try by using `create-react-native-app`
1. require `react-primitives` in your code.
2. enable minify mode by edit setting file in `./.expo/settings.json` with:
```javascript
{
  ...
  "minify": true,
  ...
}
```
3. start a project with `yarn start` or `npm start` in your console
4. access a project with your phone or access to **bundleUrl** directly on your browser

This error occurs on both platforms.

**Comment by ljharb** [comment]
If you figure this out, you can use https://npmjs.com/uglify-register to perform a regression test :-)
